name: Publish prod image

on:
  push:
    branches:
      - main

jobs:

  build:
    name : build main branch
    permissions: write-all
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: node Build
        run: npm install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t lgbd-web .

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: univ-smb-m1-isc-2023/lgbd-web/main
          tags: latest